# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/BRAM/BRAM.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM || ORIG_REF_NAME==BRAM}]

# IP: bd/BRAM/ip/BRAM_blk_mem_gen_0_0/BRAM_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_blk_mem_gen_0_0 || ORIG_REF_NAME==BRAM_blk_mem_gen_0_0}]

# XDC: bd/BRAM/BRAM_ooc.xdc
